# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tifa's Blog
subtitle: Computer & Math
description: A blog about CP & math
keywords:
author: Tifa
language: zh-CN
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://tifa-233.xyz
root: /
# permalink: :year/:month/:day/:title/
permalink: archives/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  auto_detect: false
  line_number: true
  tab_replace: "    "
  exclude_languages:
    - mermaid
    - ignore
    - graphviz
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""
  exclude_languages:
    - mermaid
    - ignore
    - graphviz

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date
  pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""

sidebar:
  # left | right (only for Pisces | Gemini).
  position: left

social:
  # GitHub: https://github.com/Tiphereth-A || github

social_icons:
  enable: false
  icons_only: false

  b2t: true
  scrollpercent: true

auto_excerpt:
  enable: true
  length: 50

read_more_btn: true

codeblock:
  border_radius:
  copy_button:
    enable: true
    show_result: true

# Extensions

search:
  path: search.xml
  field: post
  content: true
  format: html
  limit: 10000

sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  template: ./source/_data/sitemap_template.xml
  template_txt: ./source/_data/sitemap_template.txt
  rel: false
  tags: true
  categories: true

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

pandoc:
  pandoc_path: pandoc

## Hexo-minify Default Config Options
minify:
  js:
    enable: true
    ## 详细配置: https://github.com/mishoo/UglifyJS
    options:
  css:
    enable: true
    ## 详细配置: https://github.com/clean-css/clean-css#compatibility-modes
    options:
  html:
    enable: true
    ## 详细配置: https://github.com/kangax/html-minifier#options-quick-reference
    options:
      minifyJS: true # Compressed JavaScript
      minifyCSS: true # CSS Compressed
      removeComments: true # Remove the comments
      collapseWhitespace: true # Delete any extra space
      removeAttributeQuotes: true # Delete attribute quotes
  postcss:
    enable: true
    ## 详细配置: https://github.com/postcss/autoprefixer#options
    ## 注意Hexo-minify仅内置了autoprefixer插件
    ## 受Hexo限制，目前无法实现自定义postcss插件
    options:
      # JavaScript 数组写法
      # overrideBrowserslist: ['> 1%', 'last 2 versions', 'not dead']
      # YAML 数组写法
      overrideBrowserslist:
        - "> 1%" # 特殊符号需要使用'或"
        - last 2 versions
        - not dead

nofollow:
  enable: true
  field: site
  exclude:

# DOC: https://www.u2sb.top/docs/hexo-tag-mmedia
mmedia:
  aplayer:
    cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
    style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
    default:
  meting:
    cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js
    api:
    default:
  dplayer:
    cdn: https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js
    style_cdn: https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.css
    hls_cdn: https://cdn.jsdelivr.net/npm/hls.j/dist/hls.min.js
    dash_cdn: https://cdn.jsdelivr.net/npm/dashjs/dist/dash.all.min.js
    shaka_dash_cdn: https://cdn.jsdelivr.net/npm/shaka-player/dist/shaka-player.compiled.js
    flv_cdn: https://cdn.jsdelivr.net/npm/flv.js/dist/flv.min.js
    webtorrent_cdn: https://cdn.jsdelivr.net/npm/webtorrent/webtorrent.min.js
    default:

icodeweb:
  lang_default: plaintext
  types:
    - name: cpa
      lang_default:
      website: https://raw.githubusercontent.com
      prefix:
        - Tiphereth-A
        - CP-archives
        - main
        - src
      suffix:
      codehead: |
        ---
        Author: Tifa
        Description: From https://github.com/Tiphereth-A/CP-archives
        ---
    - name: cpa_nohead
      lang_default:
      website: https://raw.githubusercontent.com
      prefix:
        - Tiphereth-A
        - CP-archives
        - main
        - src
      suffix:
      codehead:
    - name: cpa_cpp
      lang_default: cpp
      website: https://raw.githubusercontent.com
      prefix:
        - Tiphereth-A
        - CP-archives
        - main
        - src
      suffix:
      codehead: |
        /*
         * @Author: Tifa
         * @Description: From https://github.com/Tiphereth-A/CP-archives
         */
    - name: cpa_py
      lang_default: python
      website: https://raw.githubusercontent.com
      prefix:
        - Tiphereth-A
        - CP-archives
        - main
        - src
      suffix:
      codehead: |
        """
        @Author: Tifa
        @Description: From https://github.com/Tiphereth-A/CP-archives
        """
