#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs sed -i 's/!\[](\([^\.\)]\+\?\)\.\([^\.\)]\+\?\))/![\1](\1.\2)/g'

echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

echo "$FILES" | xargs exiftool -a -m -u -U -e -F -overwrite_original_in_place -all= ||

echo "$FILES" | xargs git add

exit 0