name: Pages build test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Setup Pandoc
        run: sudo apt-get -y install pandoc
      - name: Build
        run: yarn install && yarn build
