name: Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Setup Pandoc
        run: sudo apt-get -y install pandoc
      - name: Build
        run: yarn install && yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './public'

  deploy:
    if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) }}
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
