name: Pages

on:
  push:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Super-Linter
        uses: github/super-linter@v4.9.2
        env:
          # VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: source/.*
          DEFAULT_BRANCH: master

          VALIDATE_CPP: false
          VALIDATE_CLANG_FORMAT: false

          MARKDOWN_LINTER_RULES: .markdownlint.json

  pages:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Setup Pandoc
        uses: nikeee/setup-pandoc@v1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
